--para ejecutar el script
--@C:\SQL\t4_sosaramos_matiasantonio.sql

--Conexion al sistema
CONNECT SYSTEM/admin;

--Si existe el usuario, eliminar
DROP USER matias CASCADE;

--Creacion del usuario
CREATE USER matias IDENTIFIED BY admin DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp QUOTA UNLIMITED ON users;

--Asignacion de permisos
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE ANY INDEX, CREATE VIEW, CREATE TRIGGER TO matias;

--desconectar usuario SYSTEM
DISCONNECT;

--Iniciar sesion usuario
CONNECT matias/admin;

--formato fecha
alter session set nls_date_format='dd/mm/yyyy';

--Creacion de tablas

CREATE TABLE SOCIOS(
       NROSOCIO INTEGER NOT NULL,
       NOMBRES VARCHAR2(30),
       APELLIDOS VARCHAR2(30),
       CI INTEGER UNIQUE,
       EDAD INTEGER,
       SOCIOPROPONENTE INTEGER,
       CONSTRAINT SOCIOS_NROSOCIO_PK PRIMARY KEY (NROSOCIO),
       CONSTRAINT SOCIOS_SOCIOPROP_FK FOREIGN KEY (SOCIOPROPONENTE) REFERENCES SOCIOS(NROSOCIO),
       CONSTRAINT SOCIOS_EDAD CHECK (EDAD > 18)
);

--SEQ de nrosocio
CREATE SEQUENCE SOCIOS_NROSOCIO_SEQ
       START WITH 1
       INCREMENT BY 1;

INSERT INTO SOCIOS(NROSOCIO, NOMBRES, APELLIDOS, CI, EDAD, SOCIOPROPONENTE)
VALUES(SOCIOS_NROSOCIO_SEQ.nextval,'Luis','Acosta',1111,25,null);

INSERT INTO SOCIOS(NROSOCIO, NOMBRES, APELLIDOS, CI, EDAD, SOCIOPROPONENTE)
VALUES(SOCIOS_NROSOCIO_SEQ.nextval,'Pedro','Rivaldi',2222,19,1);

INSERT INTO SOCIOS(NROSOCIO, NOMBRES, APELLIDOS, CI, EDAD, SOCIOPROPONENTE)
VALUES(SOCIOS_NROSOCIO_SEQ.nextval,'Laura','Diaz',3333,33,1);

INSERT INTO SOCIOS(NROSOCIO, NOMBRES, APELLIDOS, CI, EDAD, SOCIOPROPONENTE)
VALUES(SOCIOS_NROSOCIO_SEQ.nextval,'Leticia','Perez',4444,23,2);

INSERT INTO SOCIOS(NROSOCIO, NOMBRES, APELLIDOS, CI, EDAD, SOCIOPROPONENTE)
VALUES(SOCIOS_NROSOCIO_SEQ.nextval,'Pepe', 'Diaz', 2174741, 34, 2);

CREATE TABLE PRESTAMO(
       NROPRESTAMO INTEGER NOT NULL,
       NROSOCIO INTEGER,
       FECHA DATE,
       TASA NUMBER(2,1),
       MONTO INTEGER,
       SALDO INTEGER,
       CONSTRAINT PRESTAMO_NROPRESTAMO_PK PRIMARY KEY (NROPRESTAMO),
       CONSTRAINT PRESTAMO_NROSOCIO_FK FOREIGN KEY (NROSOCIO) REFERENCES SOCIOS(NROSOCIO),
       CONSTRAINT PRESTAMO_MONTO CHECK(MONTO > 0)
);

CREATE SEQUENCE PRESTAMO_NROPRESTAMO_SEQ
       START WITH 1
       INCREMENT BY 1;

--fecha
INSERT INTO PRESTAMO(NROPRESTAMO, NROSOCIO, FECHA, TASA, MONTO, SALDO)
VALUES(PRESTAMO_NROPRESTAMO_SEQ.nextval,1,'01/02/2017',1.2,1000000,0);

INSERT INTO PRESTAMO(NROPRESTAMO, NROSOCIO, FECHA, TASA, MONTO, SALDO)
VALUES(PRESTAMO_NROPRESTAMO_SEQ.nextval,2,'01/04/2017',1.2,1000000,500000);

INSERT INTO PRESTAMO(NROPRESTAMO, NROSOCIO, FECHA, TASA, MONTO, SALDO)
VALUES(PRESTAMO_NROPRESTAMO_SEQ.nextval,2,'05/04/2017',1.2,1000000,1000000);

INSERT INTO PRESTAMO(NROPRESTAMO, NROSOCIO, FECHA, TASA, MONTO, SALDO)
VALUES(PRESTAMO_NROPRESTAMO_SEQ.nextval,1,'01/05/2017',1.2,1000000,1000000);

INSERT INTO PRESTAMO(NROPRESTAMO, NROSOCIO, FECHA, TASA, MONTO, SALDO)
VALUES(PRESTAMO_NROPRESTAMO_SEQ.nextval,1,'01/09/2017',1.2,1000000,1000000);

CREATE TABLE CUOTA(
       NROPRESTAMO INTEGER NOT NULL,
       NROCUOTA INTEGER NOT NULL,
       FECHA_VENCE DATE,
       FECHA_PAGO DATE,
       IMPORTE INTEGER,
       CONSTRAINT CUOTA_NROPRESTAMO_NROCUOTA_PK PRIMARY KEY (NROPRESTAMO, NROCUOTA),
       CONSTRAINT CUOTA_NROPRESTAMO_FK FOREIGN KEY (NROPRESTAMO) REFERENCES PRESTAMO(NROPRESTAMO),
       CONSTRAINT CUOTA_IMPORTE CHECK (IMPORTE > 0)
);

CREATE OR REPLACE TRIGGER VERIFICAR_FECHAPAGO_CUOTA
       BEFORE UPDATE OF FECHA_PAGO ON CUOTA
       FOR EACH ROW
       BEGIN
              IF(:NEW.FECHA_PAGO > :OLD.FECHA_VENCE) THEN
                            RAISE_APPLICATION_ERROR(-20001, 'CUOTA VENCIDA!!');
              ELSE
                     UPDATE PRESTAMO SET SALDO = SALDO - :OLD.IMPORTE
                            WHERE(NROPRESTAMO = :OLD.NROPRESTAMO);
              END IF;
       END VERIFICAR_FECHAPAGO_CUOTA;
/
INSERT INTO CUOTA(NROPRESTAMO, NROCUOTA, FECHA_VENCE, FECHA_PAGO, IMPORTE)
VALUES(1,1,'01/03/2017','25/02/2017',500000);
INSERT INTO CUOTA(NROPRESTAMO, NROCUOTA, FECHA_VENCE, FECHA_PAGO, IMPORTE)
VALUES(1,2,'01/04/2017','30/03/2017',500000);
INSERT INTO CUOTA(NROPRESTAMO, NROCUOTA, FECHA_VENCE, FECHA_PAGO, IMPORTE)
VALUES(2,1,'01/05/2017','25/04/2017',500000);
INSERT INTO CUOTA(NROPRESTAMO, NROCUOTA, FECHA_VENCE, FECHA_PAGO, IMPORTE)
VALUES(2,2,'01/06/2017',null,500000);
INSERT INTO CUOTA(NROPRESTAMO, NROCUOTA, FECHA_VENCE, FECHA_PAGO, IMPORTE)
VALUES(3,1,'05/05/2017',null,500000);
INSERT INTO CUOTA(NROPRESTAMO, NROCUOTA, FECHA_VENCE, FECHA_PAGO, IMPORTE)
VALUES(3,2,'05/06/2017',null,500000);
INSERT INTO CUOTA(NROPRESTAMO, NROCUOTA, FECHA_VENCE, FECHA_PAGO, IMPORTE)
VALUES(4,1,'01/06/2017',null,500000);
INSERT INTO CUOTA(NROPRESTAMO, NROCUOTA, FECHA_VENCE, FECHA_PAGO, IMPORTE)
VALUES(4,2,'01/07/2017',null,500000);

--4
CREATE OR REPLACE VIEW VISTA_SOCIOS(NROSOCIO, NOMBRESAPELLIDOS, CI, TOTAL_PRESTAMO_OBTENIDO, TOTAL_PRESTAMO_CANCELADO, SOCIOPROPONENTE)
AS SELECT
              S1.NROSOCIO,
              S1.NOMBRES||''||S1.APELLIDOS,
              S1.CI,
              (SELECT SUM(P.MONTO) FROM PRESTAMO P
		  WHERE P.NROSOCIO = S1.NROSOCIO),
              (SELECT SUM(PC.MONTO) FROM PRESTAMO PC
		  WHERE (PC.NROSOCIO = S1.NROSOCIO AND PC.SALDO = 0)),
              S2.NOMBRES||''||S2.APELLIDOS
       	      FROM SOCIOS S1
       LEFT JOIN SOCIOS S2 ON S1.SOCIOPROPONENTE = S2.NROSOCIO
ORDER BY S1.NROSOCIO;

--5
SELECT CI, NOMBRES, APELLIDOS, EDAD FROM SOCIOS WHERE EDAD BETWEEN 25 AND 30;

--6
select
pr.nroprestamo, s1.nrosocio, s1.ci, s1.nombres, s1.apellidos , pr.monto ,  s2.nombres, s2.apellidos
from
prestamo pr JOIN socios s1 ON s1.nrosocio = pr.nrosocio LEFT JOIN socios s2 ON s1.socioproponente = s2.nrosocio
where
pr.monto = (select MAX(monto) from prestamo);

COMMIT;

DISCONNECT;
